"""Embed original TF2003 clothing ramps, without class textures or geometry.

Uses the same PCX crops / headless skins as TF2003/tools/build_tf_appearance.py.
Before writing, checks every supplied baked skin against its original source.
Run: py tools/build_tf_model_masks.py --tf-root C:/PythonProjects/TF2003
     --gamedir C:/Games/qwtf/fortress
"""
import argparse
import hashlib
import importlib.util
import json
import zlib
from pathlib import Path


def generate(tf_root, gamedir):
    spec = importlib.util.spec_from_file_location("appearance", tf_root / "tools/build_tf_appearance.py")
    assets = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(assets)
    _, width, height, body, _ = assets.split_mdl(assets.read_asset(gamedir, "progs/player.mdl"))
    body = [body[0]]
    for name in assets.CLASSES[1:]:
        w, h, pixels, _ = assets.decode_pcx(assets.read_asset(gamedir, f"skins/{name}.pcx"))
        assert w >= width and h >= height
        body.append(b"".join(pixels[y*w:y*w+width] for y in range(height)))
    _, hw, hh, head, _ = assets.split_mdl(assets.read_asset(gamedir, "progs/headless.mdl"))
    assert (hw, hh) == (width, height) and len(head) == len(body) == 10
    try:
        palette = assets.read_asset(gamedir, "gfx/palette.lmp")
    except FileNotFoundError:
        palette = assets.read_asset(gamedir.parent / "id1", "gfx/palette.lmp")
    overlay = tf_root / "assets/fortress"
    manifest = json.loads((overlay / "appearance-manifest.json").read_text())
    for kind, sources in [("tfbody", body), ("tfheadless", head)]:
        for team in range(1, 5):
            name = f"progs/{kind}{team}.mdl"
            data = (overlay / name).read_bytes()
            assert hashlib.sha256(data).hexdigest() == manifest["files"][name]["sha256"]
            _, w, h, baked, _ = assets.split_mdl(data)
            assert (w, h) == (width, height)
            for source, actual in zip(sources, baked):
                assert assets.bake(source, palette, manifest["top_colors"][team-1],
                                   manifest["bottom_colors"][team-1]) == actual, name
    runs, offsets = bytearray(), [0]
    for source in body + head:
        mask = bytes(p if 16 <= p < 32 or 96 <= p < 112 else 0 for p in source)
        runs.extend(zlib.compress(mask, 9))
        offsets.append(len(runs))
    lines = ["/* Generated by tools/build_tf_model_masks.py; original clothing ramps only. */",
             f"#define TF_MASK_WIDTH {width}", f"#define TF_MASK_HEIGHT {height}",
             "static const unsigned int tf_mask_offsets[] = {" + ",".join(map(str, offsets)) + "};",
             "static const unsigned char tf_mask_data[] = {"]
    for pos in range(0, len(runs), 24):
        lines.append("\t" + ",".join(map(str, runs[pos:pos+24])) + ",")
    lines.append("};\n")
    print(f"Verified 80 baked skins; {len(runs)} embedded mask bytes; {width}x{height}")
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tf-root", type=Path, required=True)
    parser.add_argument("--gamedir", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generate(args.tf_root, args.gamedir)
    target = Path(__file__).resolve().parents[1] / "src/tf_model_skin_masks.h"
    if args.check:
        assert target.read_text() == content
    else:
        target.write_text(content, encoding="ascii", newline="\n")
